import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";
import Aboutcard, { SkillsList } from "../components/Aboutcard";
import Classwork from "../components/Classwork";
import DesignsContainer from "../components/DesignsContainer";
import Education from "../components/Education";
import Experience from "../components/Experience";
import HeaderBar from "../components/HeaderBar";
import Introduction from "../components/Introduction";
import MediaLinks from "../components/MediaLinks";
import NoteWorthyProjects from "../components/NoteWorthyProjects";
import ProjectCardContainer from "../components/ProjectCard";
import BellevueCollegeLogo from "../public/images/BellevueCollegeLogo.png";
import CHSLogo from "../public/images/CupertinoHighLogo.jpg";
import EndevreLogo from "../public/images/endevreLogo.jpg";
import IOIntel from "../public/images/IO_Intelligence.jpg";
import PencilLogo from "../public/images/pencil.jpg";
import QuoraLogo from "../public/images/QuoraLogo.png";
import SelfEmployedLogo from "../public/images/SelfEmployedLogo.jpg";
import UIUCLogo from "../public/images/UIUC-Logo.jpg";
import UpworkLogo from "../public/images/upworkLogo.png";
import Design from "../public/svgs/Design";
import Programmer from "../public/svgs/Programmer";
import styles from "../styles/index.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Colin Zhou </title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <HeaderBar />
        <section>
          <div className={styles.intro}>
            <Introduction />
          </div>
          <div className={styles.svgContainer}>
            <Design />
            <Programmer />
          </div>
          <div className={styles.aboutCard} id="div-1">
            <Aboutcard />
          </div>
          <div className={styles.education} id="div-2">
            <h2 className={styles.educationHeader}>Education</h2>
            <Education
              logo={UIUCLogo}
              school="University of Illinois Urbana-Champaign"
              degreeLevel="Master of Computer Science"
              date="August 2022 - Present"
              activities={["CS 411 Database Project Team Lead"]}
              relevantClasses={[
                "User-Interface Design,",
                "Databases,",
                "Advanced Data Management",
              ]}
            />
            <Education
              logo={BellevueCollegeLogo}
              school="Bellevue College"
              degreeLevel="Bachelor of Science in Computer Science"
              date="September 2019 - June 2022"
              activities={["CS Student Advisory Board Treasurer"]}
              relevantClasses={[
                "Algorithms,",
                "Cloud Computing,",
                "Software Engineering,",
                "Data Structures,",
                "Computer Networks,",
                "Operating Systems,",
                "Linear Algebra,",
                "Discrete Math",
              ]}
            />
            <Education
              logo={CHSLogo}
              school="Cupertino High School"
              degreeLevel="High School Diploma"
              date="August 2015 - June 2019"
              activities={[
                "Speech and Debate Club Member,",
                "Sophomore English Tutor",
              ]}
              relevantClasses={[
                "AP Computer Science A,",
                "AP Statistics,",
                "AP Physics C: Mechanics,",
                "AP Chemistry,",
                "AP United States History",
              ]}
            />
          </div>
          <div className={styles.skillsList}>
            <SkillsList
              techList={[
                "React",
                "HTML",
                "CSS",
                "TypeScript",
                "JavaScript(ES6)",
                "SQL",
                "Node.js",
                "REST API's",
                "Redux",
                "AWS",
                "Webpack",
                "Java / Android Development",
                "MongoDB",
              ]}
              toolsList={[
                "Googling",
                "VSCode",
                "Markdown",
                "Jira",
                "Git",
                "Scrum",
                "Agile",
                "Speaking",
                "Writing",
                "Wireframes",
              ]}
              learningList={[
                "Containerization",
                "CI/CD pipeline",
                "Optimizing Performance",
                "Next.js",
                "Prototyping",
                "Unit Testing",
                "Responsive Design",
              ]}
            />
          </div>
          <div className={styles.experience} id="div-3">
            <h2 className={styles.expHeader}>Experience</h2>
            <Experience
              companyLogo={IOIntel}
              companyName="IOIntelligence"
              position="Software Engineer Intern"
              date="07/2022 - 09/2022"
              location="Bellevue, Washington, United States"
              description={[
                ` Developed a 5 page application dashboard that displays networking analytics
                from company's wireless devices worldwide. `,
                `Used Chakra UI, React for frontend and Express.js and MySQL for the backend.`,
              ]}
            />
            <Experience
              companyLogo={PencilLogo}
              companyName="Molloy Moreno LLC"
              position="Software Engineer Intern"
              date="06/2021 - 09/2021"
              location="Issaquah, Washington, United States"
              description={[
                `Developed a serverless web app for New York school \n 
                teachers to track the academic progress of at-risk students.`,

                `Made final design choices for UI components.`,

                `Used React to implement UI components on the frontend and AWS for storing media 
                on the backend.`,
              ]}
            />
            <Experience
              companyLogo={EndevreLogo}
              companyName="Endevre Technologies"
              position="Head of Marketing / Designer"
              date="06/2017 - 05/2018"
              location="Cupertino, California. United States"
              description={[
                `Promoted company products through emails, and by giving presentations at events.`,

                `Secured sponsorships with multiple hackathon events at high schools throughout the Bay Area.`,

                `Designed company websites and page layouts for products.`,
              ]}
            />
            <Experience
              companyLogo={BellevueCollegeLogo}
              companyName="Bellevue College"
              position="CS Student Advisory Board Member"
              date="08/2021 - 06/2022"
              location="Bellevue, Washington, United States"
              description={[
                `Met with 3 members of faculty to discuss how to grow Bellevue College CS (currently at 150 students).`,

                `Helped facilitate constructive communication between faculty and students with regards to curriculum.`,

                `Planned out $1000 budget for CS department use in 2023. Tracked all expenses using Microsoft Excel.`,
              ]}
            />
            <Experience
              companyLogo={SelfEmployedLogo}
              companyName="My House"
              position="Hobbyist Designer / Web Developer"
              date="08/2020 - present"
              location="Issaquah, Washington, United States"
              description={[
                `Created websites / designs using technologies like React,
                UI frameworks like Semantic UI, and Typescript.`,

                `Used the Google Chrome API to create a Google Chrome extension to block YouTube recommendations.`,

                `Developed a replica of the popular Microsoft Wordament game using Typescript, and React.`,
              ]}
            />
            <Experience
              companyLogo={QuoraLogo}
              companyName="Quora"
              position="Freelance Writer"
              date="08/2017 - 03/2020"
              location="Issaquah, Washington, United States"
              description={[
                `Writing about history, and other topics, with over 25 million answer views since 2017.`,

                `Managing own blog about futuristic technology, over 30k followers.`,

                `Admin and moderator of multiple blogs about finance and interesting information.`,
              ]}
            />
            <Experience
              companyLogo={UpworkLogo}
              companyName="Upwork"
              position="Freelance Writer"
              date="06/2019 - 08/2019"
              location="Issaquah, Washington, United States"
              description={[
                `Assisted clients with publishing articles on Quora.`,

                `Utilized communication skills to deliver clients work on time.`,

                `Used outreach abilities on Quora to drive traffic to client's websites.`,
              ]}
            />
            <Experience
              companyLogo={CHSLogo}
              companyName="Cupertino High School"
              position="Writing Tutor"
              date="08/2017 - 02/2018"
              location="Cupertino, California, United States"
              description={[
                `Helped tutor Cupertino High School sophomores with improving their writing.`,
                `Coordinated with high school/college teachers with tutoring progress.`,
              ]}
            />
          </div>
          <div className={styles.projects} id="div-4">
            <h2 className={styles.expHeader}>My Projects</h2>
            <ProjectCardContainer />
          </div>
          <div className={styles.moreProjects}>
            <h2 className={styles.moreProjHeader}>Noteworthy Projects</h2>
            <NoteWorthyProjects />
          </div>
          <div className={styles.classwork}>
            <h2 className={styles.classworkHeader}>Classwork</h2>
            <Classwork />
          </div>
          <div className={styles.designs} id="div-5">
            <DesignsContainer />
          </div>
          <div className={styles.icons}>
            <h2>Where to reach me!</h2>
            <MediaLinks />
          </div>
        </section>
        <div id="progressBar"></div>
        <Script src="rollingBar/headerbar.js" type="text/javascript" />
      </main>
      <footer className={styles.footer}>
        <div>
          <i>all work &copy; Colin Zhou 2020-present - all rights reserved</i>
        </div>
      </footer>
    </div>
  );
};

export default Home;
